### ISSUE TITLE
Not able to import messages

### ISSUE THREAD

**Issue by kalpeshtawde** [trp07/messages#27]
Not able to import messages module.
It has dependency on jsonconfig-tools, which is failing

```
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import messages
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ktawde/.local/lib/python3.8/site-packages/messages/__init__.py", line 7, in <module>
    from .api import send
  File "/home/ktawde/.local/lib/python3.8/site-packages/messages/api.py", line 3, in <module>
    from .email_ import Email
  File "/home/ktawde/.local/lib/python3.8/site-packages/messages/email_.py", line 15, in <module>
    from ._config import check_config_file
  File "/home/ktawde/.local/lib/python3.8/site-packages/messages/_config.py", line 12, in <module>
    import jsonconfig
  File "/home/ktawde/.local/lib/python3.8/site-packages/jsonconfig/__init__.py", line 7, in <module>
    from .core import Config
  File "/home/ktawde/.local/lib/python3.8/site-packages/jsonconfig/core.py", line 11, in <module>
    from .jsonutils import to_json_file, from_json_file
  File "/home/ktawde/.local/lib/python3.8/site-packages/jsonconfig/jsonutils.py", line 29, in <module>
    to_json = box._to_json
AttributeError: module 'box' has no attribute '_to_json'

```

**Comment by trp07** [comment]
Fixed with version 0.7.0, uploaded to PyPI.
